nombres=["juan", "carla", "ricardo", "maria"]
print (nombres)
print(len(nombres))
print(nombres[0])
print(nombres[1])
print(nombres[2])
print(nombres[3])
print(nombres[-1])
print(nombres[-2])
print(nombres[-3])
print(nombres[-4])